Fix potential unaligned access in challenge_auth.
DMTF/libspdm pull request #1165
Opened 2022-08-27 02:48 UTC by jyao1

Fix: https://github.com/DMTF/libspdm/issues/1160

Add libspdm_{read|write}_uint{16|32|64}

It can be used for unaligned access or big endian later.

Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>

2022-08-27 23:41 UTC, steven-bellock requested changes

2022-08-27 23:41 UTC, steven-bellock commented on include/library/spdm_common_lib.h
> + * @return The 16-bit value to write to buffer.
Remove line.

2022-08-27 23:41 UTC, steven-bellock commented on include/library/spdm_common_lib.h
> + * @return The 32-bit value to write to buffer.
Remove line.

2022-08-27 23:41 UTC, steven-bellock commented on include/library/spdm_common_lib.h
> + * @return The 64-bit value to write to buffer.
Remove line.

2022-08-27 23:41 UTC, steven-bellock commented on library/spdm_common_lib/libspdm_com_support.c
> + * @return The 16-bit value to write to buffer.
Remove line.

2022-08-27 23:41 UTC, steven-bellock commented on library/spdm_common_lib/libspdm_com_support.c
> +    return;
Remove unneeded `return`.

2022-08-27 23:41 UTC, steven-bellock commented on library/spdm_common_lib/libspdm_com_support.c
> + * @return The 32-bit value to write to buffer.
Remove line.

2022-08-27 23:41 UTC, steven-bellock commented on library/spdm_common_lib/libspdm_com_support.c
> +    return;
Remove unneeded return.

2022-08-27 23:41 UTC, steven-bellock commented on library/spdm_common_lib/libspdm_com_support.c
> + * @return The 64-bit value to write to buffer.
Remove line.

2022-08-27 23:41 UTC, steven-bellock commented on library/spdm_common_lib/libspdm_com_support.c
> +    return;
Remove unneeded return.

2022-08-27 23:46 UTC, steven-bellock commented
The pattern `*(uintXX_t *)` is used sparsely enough that this should be ok in the near-term. However we should migrate to something more optimized. In particular if a system is both little-endian and allows for unaligned accesses then there should be no additional overhead from using these functions. This would be accomplished by 1. macro definitions and 2. placing the functions in headers and have them made `inline`. (If you believe in that keyword.)

2022-08-28 01:20 UTC, jyao1 commented on include/library/spdm_common_lib.h
> + * @return The 16-bit value to write to buffer.
done

2022-08-28 01:21 UTC, jyao1 commented on include/library/spdm_common_lib.h
> + * @return The 32-bit value to write to buffer.
done

2022-08-28 01:21 UTC, jyao1 commented on include/library/spdm_common_lib.h
> + * @return The 64-bit value to write to buffer.
done

2022-08-28 01:21 UTC, jyao1 commented on library/spdm_common_lib/libspdm_com_support.c
> + * @return The 16-bit value to write to buffer.
done

2022-08-28 01:21 UTC, jyao1 commented on library/spdm_common_lib/libspdm_com_support.c
> +    return;
done

2022-08-28 01:21 UTC, jyao1 commented on library/spdm_common_lib/libspdm_com_support.c
> +    return;
done

2022-08-28 01:21 UTC, jyao1 commented on library/spdm_common_lib/libspdm_com_support.c
> + * @return The 64-bit value to write to buffer.
done

2022-08-28 01:22 UTC, jyao1 commented on library/spdm_common_lib/libspdm_com_support.c
> +    return;
done

2022-08-28 14:00 UTC, steven-bellock approved these changes

2022-08-28 14:11 UTC, merged