Add LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP/ENCAP_CAP
DMTF/libspdm pull request #1316
Opened 2022-10-29 16:39 UTC by jyao1

They will control encapsulated message in mutual authentication.

Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>

This is for further size optimization. Result below:

1) default
```
10/29/2022  10:23 PM            33,792 test_size_of_spdm_requester.exe
10/29/2022  10:24 PM            45,056 test_size_of_spdm_responder.exe
``

2) Set 0 to LIBSPDM_ENABLE_CAPABILITY_CHAL_CAP, LIBSPDM_ENABLE_CAPABILITY_PSK_EX_CAP, LIBSPDM_ENABLE_CAPABILITY_GET_CSR_CAP, LIBSPDM_ENABLE_CAPABILITY_SET_CERTIFICATE_CAP, LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP
```
10/29/2022  11:03 PM            29,184 test_size_of_spdm_requester.exe
10/29/2022  11:03 PM            35,328 test_size_of_spdm_responder.exe
```

3) Continue 2), set 0 to LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP, LIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP
```
10/30/2022  12:18 AM            24,576 test_size_of_spdm_requester.exe
10/30/2022  12:18 AM            30,720 test_size_of_spdm_responder.exe
```

2022-10-29 16:53 UTC, steven-bellock requested changes

2022-10-29 16:53 UTC, steven-bellock commented on include/internal/libspdm_requester_lib.h
> +#if LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP || LIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP
`LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP || LIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP` -> `(LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP) || (LIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP)`

2022-10-30 00:40 UTC, jyao1 commented on include/internal/libspdm_requester_lib.h
> +#if LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP || LIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP
Done

2022-10-30 01:56 UTC, steven-bellock approved these changes

2022-10-30 03:44 UTC, merged