os_stub/openssllib: Support more archetectures
DMTF/libspdm pull request #2011
Opened 2023-05-03 02:56 UTC by alistair23

2023-05-03 06:38 UTC, jyao1 approved these changes

2023-05-03 21:44 UTC, steven-bellock requested changes
Does libspdm's instance of OpenSSL even work on `arc` / `arm`?

2023-05-03 21:44 UTC, steven-bellock commented on os_stub/cryptlib_openssl/CMakeLists.txt
> +    MESSAGE(FATAL_ERROR "Unkown ARCH")
`Unkown` -> `Unknown`

2023-05-03 21:44 UTC, steven-bellock commented on os_stub/openssllib/CMakeLists.txt
> +    MESSAGE(FATAL_ERROR "Unkown ARCH")
`Unkown` -> `Unknown`

2023-05-04 05:06 UTC, alistair23 commented
I have dropped the `arc` and `arm`. I suspect they would work, but I can't test it

2023-05-04 14:08 UTC, steven-bellock commented
For better or worse libspdm uses the UEFI profile of OpenSSL, which helps it fit into more limited systems.

2023-05-04 14:09 UTC, steven-bellock approved these changes

2023-05-05 00:47 UTC, merged