CMakeLists: Allow disabling tests
DMTF/libspdm pull request #2120
Opened 2023-06-13 05:08 UTC by alistair23

Add support for disabling the tests. If building libspdm as a library (for example in buildroot) we often don't want to build the tests, so add the option to disable the tests.

2023-06-13 06:16 UTC, jyao1 commented
Would you please also update readme to show how to use this feature?

2023-06-13 06:27 UTC, alistair23 commented
Done

2023-06-13 14:30 UTC, steven-bellock requested changes
This needs to be added to either https://github.com/DMTF/libspdm/blob/main/.github/workflows/build.yml or maybe create another workflow that just builds libspdm without tests.

2023-06-13 14:30 UTC, steven-bellock commented on doc/build.md
> +If you don't want to build or run the unit tests they can be disabled by adding the following to the cmake command
"Unit tests can be disable by adding `-DDISABLE_TESTS=1` to CMake."

2023-06-14 03:02 UTC, alistair23 commented
I have added tests to the GitHub actions

2023-06-14 14:40 UTC, jyao1 commented
@steven-bellock , we should not do "Merge branch"

2023-06-14 19:33 UTC, steven-bellock commented
> @steven-bellock , we should not do "Merge branch"

Yeah that was Github. I'll revert.

2023-06-14 22:08 UTC, alistair23 commented
I have rebased the PR

2023-06-15 01:18 UTC, steven-bellock approved these changes

2023-06-15 02:05 UTC, merged