library: Include base_*_algo to libspdm_write_certificate_to_nvm()
DMTF/libspdm pull request #2142
Opened 2023-06-16 03:06 UTC by alistair23

If the implementor wants to update the certificate without rebooting the device they will need to know the base_hash_algo and base_asym_algo in order to verify and hash the new certificate. Let's pass that information to the libspdm_write_certificate_to_nvm() function so that it can use it.

2023-06-16 17:32 UTC, steven-bellock requested changes

2023-06-16 17:32 UTC, steven-bellock commented on include/hal/library/responder_secretlib.h
> + * @param[in]  base_asym_algo   Indicates the hash algorithm.
"Indicates all supported hash algorithms."

2023-06-16 17:32 UTC, steven-bellock commented on library/spdm_responder_lib/libspdm_rsp_set_certificate.c
> +                                              spdm_context->local_context.algorithm.base_asym_algo,
`spdm_context->connection_info.algorithm.base_asym_algo`, else there might be multiple algorithms in the bitmask.

2023-06-20 07:08 UTC, jyao1 commented
Seems good idea.

2023-06-21 05:23 UTC, jyao1 commented
@alistair23, would you please update the patch according to the feedback?

2023-06-22 03:52 UTC, alistair23 commented
Sorry, it's been a busy week. All updated

2023-06-26 14:45 UTC, jyao1 commented on library/spdm_responder_lib/libspdm_rsp_set_certificate.c
> +                                              spdm_context->local_context.algorithm.base_hash_algo);
I suggest we change `base_hash_algo` to negotiated one as well.
Please use `connection_info.algorithm.base_hash_algo`, that is the only way to indicate what root-hash is in the certificate.

2023-06-26 14:45 UTC, steven-bellock commented
This pull request is conditional on #2134.
Also, @jyao1 and I discussed this and `base_hash_algo` shoud be `base_hash_sel`, the negotiated algorithm.

2023-06-27 00:25 UTC, alistair23 commented
Done!

2023-06-27 01:04 UTC, jyao1 approved these changes

2023-06-27 01:04 UTC, merged