doc: user_guide: update api usage and fixup typos
DMTF/libspdm pull request #2297
Opened 2023-08-02 02:43 UTC by twilfredo

2023-08-02 02:45 UTC, jyao1 approved these changes

2023-08-02 17:34 UTC, steven-bellock requested changes

2023-08-02 17:34 UTC, steven-bellock commented on doc/user_guide.md
> +   Optional, the Integrator can calculate the `scratch_buffer_size` according to the `max_spdm_msg_size` value input to `libspdm_register_transport_layer_func()`, according to `libspdm_get_scratch_bu
`Optionally`

2023-08-03 01:18 UTC, twilfredo commented on doc/user_guide.md
> +   Optional, the Integrator can calculate the `scratch_buffer_size` according to the `max_spdm_msg_size` value input to `libspdm_register_transport_layer_func()`, according to `libspdm_get_scratch_bu
Woops! fixed

2023-08-03 14:42 UTC, steven-bellock approved these changes

2023-08-03 14:43 UTC, merged