Add new DMTFSpecMeasurementValueType for SPDM 1.3
DMTF/libspdm pull request #2415
Opened 2023-10-19 10:52 UTC by Wenxing-hou

Fix: #2286

2023-10-20 01:59 UTC, jyao1 approved these changes

2023-10-20 15:20 UTC, steven-bellock requested changes

2023-10-20 15:20 UTC, steven-bellock commented on include/industry_standard/spdm.h
> +#define SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_STRUCTURED_MEASUREMENT_MANIFEST 0xA
`0xA` -> `10`.

2023-10-23 06:44 UTC, Wenxing-hou commented on include/industry_standard/spdm.h
> +#define SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_STRUCTURED_MEASUREMENT_MANIFEST 0xA
Thanks. I have changed it.

2023-10-23 14:02 UTC, merged