DIGEST: add KeyPairID and CertificateInfo
DMTF/libspdm pull request #2445
Opened 2023-11-29 12:36 UTC by jyao1

Fix https://github.com/DMTF/libspdm/issues/2285

2023-12-02 00:06 UTC, steven-bellock requested changes

2023-12-02 02:51 UTC, jyao1 commented on include/industry_standard/spdm.h
> +#define SPDM_CERTIFICATE_INFO_CERT_MODEL_GENERIC_CERT 0x4
good catch!
Fixed.

2023-12-03 23:55 UTC, steven-bellock commented on library/spdm_requester_lib/libspdm_req_get_digests.c
> +        for (index = 0; index < digest_count; index++) {
`digest_count` -> `SPDM_MAX_SLOT_COUNT`

2023-12-04 15:35 UTC, steven-bellock approved these changes

2023-12-05 00:45 UTC, merged