Add key_pair_id for libspdm_gen_csr_ex
DMTF/libspdm pull request #2551
Opened 2024-02-02 01:43 UTC by Wenxing-hou

Fix: #2550

2024-02-02 17:00 UTC, steven-bellock requested changes

2024-02-04 02:04 UTC, Wenxing-hou commented on include/hal/library/responder/csrlib.h
> + * @param[in]       key_pair_id           The value of this field shall be the unique key pair number identifying the desired
Thanks. That's right.  I have changed the code.

2024-02-04 22:05 UTC, steven-bellock commented on include/hal/library/responder/csrlib.h
> + * @param[in]       key_pair_id           The value of this field shall be the unique key pair number identifying the desired
Also change the text from
>The value of this field shall be the unique key pair number identifying the desired asymmetric key pair to associate with SlotID.

to
>Indicates the desired key pair associated with the CSR.

There is no SlotID associated with a CSR.

2024-02-05 02:44 UTC, Wenxing-hou commented on include/hal/library/responder/csrlib.h
> + * @param[in]       key_pair_id           The value of this field shall be the unique key pair number identifying the desired
Thanks. I have updated the comment.

2024-02-21 15:21 UTC, steven-bellock approved these changes

2024-02-22 07:40 UTC, merged