Add and update fuzzy tests
DMTF/libspdm pull request #323
Opened 2021-11-30 09:09 UTC by Xiaohanjlll

2021-11-30 17:59 UTC, steven-bellock requested changes
You can delete all instances of ${LIBSPDM_DIR}/include/hal  That is no longer required as an include path.

2021-11-30 17:59 UTC, steven-bellock commented on unit_test/fuzzing/test_spdm_requester_encap_key_update/CMakeLists.txt
> +                    ${LIBSPDM_DIR}/include
Delete redundant line.

2021-12-01 03:30 UTC, Xiaohanjlll commented on unit_test/fuzzing/test_spdm_requester_encap_key_update/CMakeLists.txt
> +                    ${LIBSPDM_DIR}/include
Thanks.I have deleted redundant line.

2021-12-01 22:42 UTC, steven-bellock approved these changes

2021-12-02 01:51 UTC, merged