Document platform_lib usage.
DMTF/libspdm pull request #636
Opened 2022-02-14 13:28 UTC by qizhangz

Fix: #607 

Signed-off-by: Qi Zhang <qi1.zhang@intel.com>

2022-02-15 02:11 UTC, jyao1 commented
I will let @steven-bellock review

2022-02-15 18:43 UTC, steven-bellock requested changes

2022-02-15 18:43 UTC, steven-bellock commented on doc/design.md
> +   The sleep function delays the execution of a message flow instance for a defined period of time in milliseconds.
Can just be
>The sleep function delays the execution of a message flow instance for a defined period of time.

2022-02-16 07:52 UTC, qizhangz commented on doc/design.md
> +   The sleep function delays the execution of a message flow instance for a defined period of time in milliseconds.
done

2022-02-16 15:42 UTC, steven-bellock approved these changes

2022-02-17 00:43 UTC, merged