MajorVersion and MinorVersion is coming from external input and it ma…
DMTF/libspdm pull request #712
Opened 2022-03-08 09:36 UTC by Zhiqiang520

…ybe greater than ten.
fix: #699
Signed-off-by: Zhao, Zhiqiang <zhiqiang.zhao@intel.com>

2022-03-08 11:36 UTC, jyao1 commented
Would you please clarify the call stack for this error?

How the version is propagated from external to this libspdm_create_signing_context()?

I think checking version should be the first step for every command/response...

2022-03-09 01:11 UTC, Zhiqiang520 commented
The call stack for this error is as following:
```
    #4 0x56384c in libspdm_debug_assert /home/test/libspdm/os_stub/debuglib/debuglib.c:43:9
    #5 0x58fdad in libspdm_create_signing_context /home/test/libspdm/library/spdm_crypt_lib/libspdm_crypt_crypt.c:1620:5
    #6 0x592f8a in libspdm_req_asym_sign /home/test/libspdm/library/spdm_crypt_lib/libspdm_crypt_crypt.c:3048:9
    #7 0x59eaa0 in libspdm_requester_data_sign /home/test/libspdm/os_stub/spdm_device_secret_lib_sample/lib.c:739:18
    #8 0x561b74 in libspdm_test_responder_finish_case8 /home/test/libspdm/unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c:387:5
    #9 0x56233c in libspdm_run_test_harness /home/test/libspdm/unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c:433:5
```

2022-03-09 01:23 UTC, jyao1 commented
OK. The issue is at 
 #8 0x561b74 in libspdm_test_responder_finish_case8 /home/test/libspdm/unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c:387:5

```
        m_spdm_finish_request.header.spdm_version << SPDM_VERSION_NUMBER_SHIFT_BIT, SPDM_FINISH,
```

You cannot input fuzzed version. It is illegal configuration.

2022-03-09 01:27 UTC, jyao1 commented on library/spdm_crypt_lib/libspdm_crypt_crypt.c
> +    if ((((spdm_version >> 12) & 0xF) >= 10) ||
This is internal function.

The caller need guarantee the version is correct.

2022-03-09 01:27 UTC, jyao1 requested changes
Please make sure the caller is correct.

2022-03-09 05:50 UTC, jyao1 commented on unit_test/fuzzing/test_responder/test_spdm_responder_finish_rsp/finish_rsp.c
> +        m_spdm_finish_request.header.spdm_version = SPDM_MESSAGE_VERSION_11;
I recommend to change to VERSION_12.

2022-03-09 05:51 UTC, jyao1 approved these changes

2022-03-09 05:51 UTC, jyao1 commented
Merge, since it is test code only.

2022-03-09 05:52 UTC, merged