Change the basic constrains len by considering optional INTEGER
DMTF/libspdm pull request #955
Opened 2022-06-17 10:13 UTC by Wenxing-hou

Fix: #951 

Signed-off-by: Wenxing Hou <wenxing.hou@intel.com>

2022-06-17 12:04 UTC, jyao1 requested changes
This is not right. You cannot use the size of local machine.
Also you x5.09 uses DER encoding.

Please do some test before submit patch.

2022-06-21 03:39 UTC, jyao1 commented on library/spdm_crypt_lib/libspdm_crypt_crypt.c
> +#define BASIC_CONSTRAINTS_CA_LEN 2
I think we need change this to 5, with comment below:
+--------------------------------------------+
| seq | seq_len | bool | bool_len | bool_val |
+--------------------------------------------+
| 30 |   03  | 01 |  01  | 00/ff |
+--------------------------------------------+

2022-06-21 03:39 UTC, jyao1 commented on library/spdm_crypt_lib/libspdm_crypt_crypt.c
> +#define BASIC_CONSTRAINTS_MAX_LEN sizeof(size_t) + BASIC_CONSTRAINTS_CA_LEN
please remove this.

2022-06-21 03:42 UTC, jyao1 commented on library/spdm_crypt_lib/libspdm_crypt_crypt.c
> +#define BASIC_CONSTRAINTS_CA_LEN 2
please also add description on why optional length is not meaningful, with URL.

2022-06-21 13:04 UTC, jyao1 commented on library/spdm_crypt_lib/libspdm_crypt_crypt.c
> +#define LIBSPDM_BASIC_CONSTRAINTS_STRING_CASE2 {0x30, 0x00, 0x01, 0x01, 0x00}
The second bytes is not correct.

2022-06-23 02:15 UTC, Wenxing-hou commented on unit_test/test_spdm_crypt/test_spdm_crypt.c
> +         **/
I comment out the code. So the libspdm_test_crypt_spdm_get_dmtf_subject_alt_name unit test check has not been processed.

2022-06-23 03:28 UTC, jyao1 commented on unit_test/test_spdm_crypt/test_spdm_crypt.c
> +         **/
I am asking why you comment code. Why no make it pass?

2022-06-24 08:43 UTC, jyao1 commented on include/library/spdm_crypt_lib.h
> +    char **name_buffer, size_t *name_buffer_size, uint8_t *oid,
Please dont change API.

2022-06-24 08:43 UTC, jyao1 commented on include/library/spdm_crypt_lib.h
> +                                  char **name_buffer,
Please dont change API.

2022-06-24 08:44 UTC, jyao1 requested changes
Changing API is not allowed.

2022-06-26 03:34 UTC, Wenxing-hou commented on include/library/spdm_crypt_lib.h
> +                                  char **name_buffer,
Thanks. I have fixed the issue.

2022-06-27 00:46 UTC, merged